train_data_dir: /usr/data
train_start_idx: 0
num_train: 2
val_data_dir: /usr/data
val_start_idx: 2
num_val: 2
test_data_dir: /usr/data
test_start_idx: 4
num_test: 1
log_dir: /usr/logs

params:
    initial_val: False
    pos_encoding: "none"  # nerf, none, gaussian
    side_length: [174, 208, -1, 1]
    max_epochs: 1201
    log_interval: 2
    val_interval: 2
    fine_tune_max_epochs: 5  # Lightning is faster doing (2000 epochs x 1 batch) than (1 epoch x 2000 batches)
    fine_tune_log_interval: 5
    x_holdout_rate: 2  # Height
    y_holdout_rate: 2  # Width
    z_holdout_rate: 1  # Slices
    t_holdout_rate: 1  # Time
    lr: 1e-4
    fine_tune_lr: 1e-4
    latent_reg: 1e-4
    weight_reg: 1e-4
    activation: "wire"  # periodic, relu, wire
    wire_omega_0: 10.0
    skip_connections: True
    input_coord_to_all_layers: False
